// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSLD-O1A0jV8eNoBpUxvf8J6_AgQRoG6g',
    appId: '1:72178836284:web:047133b86732ae30ebb439',
    messagingSenderId: '72178836284',
    projectId: 'wassena-59085',
    authDomain: 'wassena-59085.firebaseapp.com',
    storageBucket: 'wassena-59085.firebasestorage.app',
    measurementId: 'G-GMG5YXSNM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoRvYh_KZyhnsVAtqGfi43oIytQ718jXk',
    appId: '1:72178836284:android:5bc851572b56a77aebb439',
    messagingSenderId: '72178836284',
    projectId: 'wassena-59085',
    storageBucket: 'wassena-59085.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPiSLD2uLvndlR0bFD7gcpamO22gibsgU',
    appId: '1:72178836284:ios:ab94a53ec40a8e72ebb439',
    messagingSenderId: '72178836284',
    projectId: 'wassena-59085',
    storageBucket: 'wassena-59085.firebasestorage.app',
    iosBundleId: 'com.example.wassena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPiSLD2uLvndlR0bFD7gcpamO22gibsgU',
    appId: '1:72178836284:ios:ab94a53ec40a8e72ebb439',
    messagingSenderId: '72178836284',
    projectId: 'wassena-59085',
    storageBucket: 'wassena-59085.firebasestorage.app',
    iosBundleId: 'com.example.wassena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSLD-O1A0jV8eNoBpUxvf8J6_AgQRoG6g',
    appId: '1:72178836284:web:faf3edcc878abf26ebb439',
    messagingSenderId: '72178836284',
    projectId: 'wassena-59085',
    authDomain: 'wassena-59085.firebaseapp.com',
    storageBucket: 'wassena-59085.firebasestorage.app',
    measurementId: 'G-2TLHQE216T',
  );
}
